### ISSUE TITLE
jitpack builds failing

### ISSUE THREAD

**Issue by GRBurst** [OutWatch/outwatch#286] opened 2019-02-12 20:23 UTC
hey,

the build are failing before even starting to compile, see https://jitpack.io/com/github/outwatch/outwatch/ea240c6/build.log

is this a jitpack issue or do you know what might cause this?

**Comment by GRBurst** [comment] 2019-02-12 20:33
seems to be a recent issue: https://github.com/jitpack/jitpack.io/issues/3733

**Comment by Busti** [comment] 2019-02-13 01:21
While I cannot provide a solution to the issue, I can provide a workaround.  
Earlier in the development of my application I stopped using jitpack altogether, since (from my experience) turnaround times are way too slow for my purposes and it can fail in all kinds of ways, which are really hard to troubleshoot.  
My project depends on a fork of outwatch and I use it as a testing ground for the changes I make (some of which #270 I am trying to get into upstream).

Since I do not want to wait anywhere between 2 Hours and 2 Days for jitpack to build my project every time I make a change, I have now switched to using sbt's `ProjectRef` to handle the retrieval of my outwatch fork.  

Specifically I use it like this:  
```scala
// Creates a reference to the outwatch project, which behaves like a sbt subproject.
lazy val outwatch = ProjectRef(uri("https://github.com/busti/outwatch.git#debug3"), "outwatch")

lazy val client = project
  .settings( ??? )
  .dependsOn(outwatch)
```

To my surprise this also seems to integrate nicely into IntelliJ, which creates a separate workspace for the `ProjectRef` and handles it like a git submodule.
![intellij screenshot](https://i.imgur.com/BdZwiKL.png)


However, there are some gotchas with this approach, which can be avoided
 * The Setting `requireJsDomEnv in Test := true` from `ScalaJSBundler` cannot be found when the ProjectRef is compiled. I avoid this by having a separate branch with a single commit which removes the setting. See https://github.com/Busti/outwatch/commit/58a5d3e55cb828215d2df1a836192b9a51ad0177  
 * Even though sbt retrieves the `ProjectRef` through a git clone, which seems to integrate nicely with IntelliJ, making changes to the files in said git repository can sometimes lead to the whole project failing to compile due to **Linking Errors**. I still do not know what causes this and it is relatively annoying to fix, since all files created by sbt for that project have to be manually removed. This includes all target folders, aswell as the place where the `ProjectRef` is cloned to, but not the .sbt folder in the home directory. Due to this issue, I currently make changes to outwach in a separate clone and sync them via remote, since sbt re-clones the `ProjectRef` every time it launches.  

I hope this can be useful to you and remind me to create an issue on ScalaJSBundler to ask them why `requireJsDomEnv` cannot be found in the context of `ProjectRef`.

**Comment by socool** [comment] 2019-02-13 04:47
I've got same issued.

**Comment by GRBurst** [comment] 2019-02-13 10:09
@Busti thanks for the detailed workaround, this is definitely an option in cases i really need a fast update :+1: 

turns out jitpack is working correctly again

**Comment by cornerman** [comment] 2019-02-17 12:11
I am goind to close this one, as it seems that it was caused by a jitpack problem. Feel free to reopen if there is something we can do.

**Closed by cornerman** 2019-02-17 12:11 UTC
