### ISSUE TITLE
problems with snabbdom version

### ISSUE THREAD

**Issue by elyphas** [OutWatch/outwatch#297] opened 2019-05-01 16:46 UTC
An error raise up when I try to update the proyect to the last commit.
```scala
[error] npm ERR! code 1
[error] npm ERR! Command failed: /usr/bin/git checkout 464535d git://github.com/cornerman/snabbdom.git#bac3e6a
[error] npm ERR! error: ruta especificada '464535d git://github.com/cornerman/snabbdom.git#bac3e6a' no concordó con ningún archivo(s) conocido por git
[error] npm ERR!
```
the problems seems to appear in the presence of 
`"com.clovellytech" %%% "outwatch-router" % "0.0.6",`
relate to two different versions

**Comment by cornerman** [comment] 2019-05-01 23:20
Thank you for opening the issue!

I have tried it out, and resolution is working with yarn, but not with npm. Can you try adding `useYarn := true` to the project in your build.sbt? 

Anyhow I think, we should have a better versioning for the git-dependency of our snabbdom fork and use tags for our version. Also, we might want to apply semantic versioning with npm and git-dependencies (https://github.com/npm/npm/pull/15308#issuecomment-314263640).

**Comment by elyphas** [comment] 2019-05-03 20:24
sorry, I can't be able to solve the problem
is almost the same error
```scala
[info] Updating NPM dependencies
[error] npm ERR! code 1
[error] npm ERR! Command failed: git checkout bac3e6a git://github.com/cornerman/snabbdom.git#464535d
[error] npm ERR! error: ruta especificada 'bac3e6a git://github.com/cornerman/snabbdom.git#464535d' no concordó con ningún archivo(s) conocido por git
```
now is:
```scala
'bac3e6a git://github.com/cornerman/snabbdom.git#464535d' 
```
before was:
```scala
464535d git://github.com/cornerman/snabbdom.git#bac3e6a
```

**Comment by elyphas** [comment] 2019-05-03 21:15
by the way, about this:
`Can you try adding useYarn := true to the project in your build.sbt?`
yes I tried, no success

**Comment by elyphas** [comment] 2019-05-03 21:49
I also tried installing snabbdom with `npm install git`

**Comment by cornerman** [comment] 2019-05-04 12:08
@elyphas I have added a commit to semantic versioning with the snabbdom git-dependency. Can you try depending on this outwatch version? `"com.github.cornerman" % "outwatch" % "ee5804fc"`

**Comment by elyphas** [comment] 2019-05-04 17:31
Sorry, now other error:
```scala
[error] npm ERR! Only tag, version, and range are supported
[error] npm ERR! A complete log of this run can be found in:
[error] npm ERR!     /home/elyphas/.npm/_logs/2019-05-04T17_24_10_449Z-debug.log
[error] java.lang.RuntimeException: Non-zero exit code: 1
```
seems this line is the problem:
```scala
1309 silly saveTree main
1309 silly saveTree └── jsdom@9.9.0
1310 verbose stack Error: Only tag, version, and range are supported
```

**Comment by elyphas** [comment] 2019-05-04 17:43
sorry, seems is more bigger the block related:
```scala
1304 silly pacote version manifest for jsdom@9.9.0 fetched in 17ms
1305 silly resolveWithNewModule jsdom@9.9.0 checking installable status
1306 silly fetchPackageMetaData error for snabbdom@git://github.com/cornerman/snabbdom.git#semver:0.7.3 git://github.com/cornerman/snabbdom.git#bac3e6a Only tag, version, and range are supported
1307 timing stage:rollbackFailedOptional Completed in 1ms
1308 timing stage:runTopLevelLifecycles Completed in 8557ms
1309 silly saveTree main
1309 silly saveTree └── jsdom@9.9.0
1310 verbose stack Error: Only tag, version, and range are supported
1310 verbose stack     at pickManifest (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:51:11)
```

**Comment by elyphas** [comment] 2019-05-04 19:39
@cornerman ; Could You tell me? please, what is the functions of this:
```scala
scalacOptions += {
    val local = baseDirectory.value.toURI
    val remote = s"https://raw.githubusercontent.com/OutWatch/outwatch/${git.gitHeadCommit.value.get}/"
    s"-P:scalajs:mapSourceURI:$local->$remote"
},
```
in the build.sbt of outwatch

**Comment by cornerman** [comment] 2019-05-04 19:41
> @cornerman ; Could You tell me? please, what is the functions of this:

This is for having proper source maps. So you have proper links to the scala files on github when debugging.

**Comment by cornerman** [comment] 2019-05-04 19:46
@elyphas I have cloned your repository https://github.com/elyphas/manik and changed the outwatch dependency to the commit as well as setting `useYarn := true`. This fixed the problem for me. Did you try with yarn, too?

**Comment by elyphas** [comment] 2019-05-04 22:12
sorry, seems I have not proper setup I set `useYarn:=true` in one of the first lines, I have a clean virtual machine, without `npm` only `yarn`, and I have this problem:

```scala
[error] (client / Compile / npmUpdate) java.io.IOException: Cannot run program "npm" (in directory "/home/elyphas/PrjsScala/manik/clien: error=2, No existe el archivo o el directorio
```

**Comment by elyphas** [comment] 2019-05-04 22:32
the last error was solved throught `npm install --global yarn`

**Comment by elyphas** [comment] 2019-05-05 00:11
I am so sorry, the same error with yarn
```scala
[info] Updating NPM dependencies
[error] yarn install v1.15.2
[error] info No lockfile found.
[error] [1/4] Resolving packages...
[error] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[error] error Couldn't find match for "bac3e6a git://github.com/cornerman/snabbdom.git" in "refs/heads/check-parent-exists,refs/heads/check-parent-exists-dist,refs/heads/equalityfn-thunk,refs/heads/fix-elm-child,refs/heads/gh-pages,refs/heads/master,refs/heads/modular,refs/heads/multiple-event-handlers,refs/heads/new-thunk,refs/heads/next,refs/heads/next2,refs/heads/patch-under-container,refs/heads/replace-root,refs/heads/set-boolean-attributes-correctly,refs/heads/type-tweaks,refs/tags/0.7.3,refs/tags/v0.2.2,refs/tags/v0.2.3,refs/tags/v0.2.7,refs/tags/v0.2.8,refs/tags/v0.3.0,refs/tags/v0.3.1,refs/tags/v0.3.2,refs/tags/v0.3.3,refs/tags/v0.3.4,refs/tags/v0.4.0,refs/tags/v0.4.1,refs/tags/v0.4.2,refs/tags/v0.5.0,refs/tags/v0.5.1,refs/tags/v0.5.2,refs/tags/v0.5.3,refs/tags/v0.5.4,refs/tags/v0.6.0,refs/tags/v0.6.1,refs/tags/v0.6.2,refs/tags/v0.6.3,refs/tags/v0.6.4,refs/tags/v0.6.5,refs/tags/v0.6.6,refs/tags/v0.6.7,refs/tags/v0.6.8,refs/tags/v0.6.9,refs/tags/v0.7.0,refs/tags/v0.7.1,refs/tags/v0.7.2,refs/tags/v0.7.3" for "https://github.com/cornerman/snabbdom.git".
[error] java.lang.RuntimeException: Non-zero exit code: 1
```

**Comment by elyphas** [comment] 2019-05-05 00:15
```scala
[info] Updating NPM dependencies
[error] yarn install v1.15.2
[error] info No lockfile found.
[error] [1/4] Resolving packages...
[error] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[error] error Couldn't find match for "bac3e6a git://github.com/cornerman/snabbdom.git" in 
"
refs/heads/check-parent-exists,
refs/heads/check-parent-exists-dist,
refs/heads/equalityfn-thunk,
refs/heads/fix-elm-child,
refs/heads/gh-pages,
refs/heads/master,
refs/heads/modular,
refs/heads/multiple-event-handlers,
refs/heads/new-thunk,
refs/heads/next,
refs/heads/next2,
refs/heads/patch-under-container,
refs/heads/replace-root,
refs/heads/set-boolean-attributes-correctly,
refs/heads/type-tweaks,
refs/tags/0.7.3,
refs/tags/v0.2.2,
refs/tags/v0.2.3,
refs/tags/v0.2.7,
refs/tags/v0.2.8,
refs/tags/v0.3.0,
refs/tags/v0.3.1,
refs/tags/v0.3.2,
refs/tags/v0.3.3,
refs/tags/v0.3.4,
refs/tags/v0.4.0,
refs/tags/v0.4.1,
refs/tags/v0.4.2,
refs/tags/v0.5.0,
refs/tags/v0.5.1,
refs/tags/v0.5.2,
refs/tags/v0.5.3,
refs/tags/v0.5.4,
refs/tags/v0.6.0,
refs/tags/v0.6.1,
refs/tags/v0.6.2,
refs/tags/v0.6.3,
refs/tags/v0.6.4,
refs/tags/v0.6.5,
refs/tags/v0.6.6,
refs/tags/v0.6.7,
refs/tags/v0.6.8,
refs/tags/v0.6.9,
refs/tags/v0.7.0,
refs/tags/v0.7.1,
refs/tags/v0.7.2,
refs/tags/v0.7.3" for "https://github.com/cornerman/snabbdom.git".
[error] java.lang.RuntimeException: Non-zero exit code: 1
```

**Comment by cornerman** [comment] 2019-05-05 10:25
Hmm, that is weird. I have forked your repo here https://github.com/cornerman/manik and added a commit to update outwatch. Without this commit, I get the same error that you are seeing. But with the commit, it works for me. Not sure, what might be different from your setup.

The steps I am doing:
```
git clean -xfd
sbt client/fastOptJS::webpack
```

Does that work for you?

**Comment by cornerman** [comment] 2019-05-05 10:30
BTW which version of yarn and npm are you running?

I am using:
```sh
$ npm -v
6.9.0
$ yarn -v
1.15.2
```

**Comment by elyphas** [comment] 2019-05-05 15:14
npm -v
6.9.0
elyphas@projs1:~$ yarn -v
1.15.2
elyphas@projs1:~$

**Comment by cornerman** [comment] 2019-05-05 15:30
> I have forked your repo here https://github.com/cornerman/manik and added a commit to update outwatch.

@elyphas Were you able to reproduce the problem in that repo?

**Comment by elyphas** [comment] 2019-05-05 15:37
the same exact problem. I have

**Comment by elyphas** [comment] 2019-05-05 15:42
it is compiled

**Comment by elyphas** [comment] 2019-05-05 15:50
I was running this way: 
`sbt ~server/run`

where `server` is a subproject in `sbt`

and leaving all it has to do to sbt,
seems it is mandatory to run `sbt client/fastOptJS::webpack ` first, although now I have trouble with the `server` subproject but at least now is more clear the path to take, 

Thank you very much. @cornerman

**Comment by cornerman** [comment] 2019-05-05 16:07
Good to hear that it starts working again.

Though, I am not sure about the reason for the server project problem. I have tried `server/run` and for me it just calls `client/fastOptJs::webpack` itself and happily compiles. Maybe you needed a `sbt clean`?

**Comment by elyphas** [comment] 2019-05-05 16:13
yes it works,
I was running `sbt ~server/run`, not works
with `sbt server/run` it works

**Comment by elyphas** [comment] 2019-05-05 16:14
by the way I had to state in certain order:
is mandatory this order:
1.-   "com.github.cornerman" % "outwatch" % "bb2dbc58",
2.-   "com.clovellytech" %%% "outwatch-router" % "0.0.6",

**Comment by elyphas** [comment] 2019-05-05 16:15
without that order the error appears

**Comment by cornerman** [comment] 2019-05-05 16:19
> by the way I had to state in certain order:

Good point! Afaik, this will go away in the future when conflicting version both use semantic versioning. Right now, the latter one does not and somehow needs this order.

**Comment by cornerman** [comment] 2019-05-05 16:21
> I was running sbt ~server/run, not works

Sadly, I cannot reproduce this. Let me know how it goes.

**Comment by elyphas** [comment] 2019-05-05 16:24
ok, I will, 

thank you very much.

**Comment by cornerman** [comment] 2019-05-07 13:09
@elyphas I have merged the snabbdom versioning PR and therefore closed this issue. If you keep on having issues, please feel free to reopen this issue!

**Closed** 2019-05-07 13:08 UTC
