### ISSUE TITLE
subscribe not working for "createHandler" outside  dom element

### ISSUE THREAD

**Issue by doofin** [OutWatch/outwatch#142] opened 2017-12-29 17:32 UTC
```scala
    import outwatch.dom._
    import rxscalajs.Observable
    
    val hd: Handler[Event] =createHandler() //sink and observable
    hd.map(x=>println("toggle"))//not working here!
    //Observable.interval(10).take(20).subscribe(x=>println("aa")) // working!
    val root = div(
      label("Hide view"),
      input(tpe := "checkbox", change --> hd),
      h2(hidden <-- hd.map(_.target.asInstanceOf[HTMLInputElement].checked).map(x=>{println("x");x}), "Visible!")
    )

    OutWatch.render(sel,root) //sel here is a selector string

```

'toggle' is not printed ,but 'x' is printed,is that expected behavior?If so,how to wire for multiple subscribers

**Comment by doofin** [comment] 2017-12-29 17:50
I find out the problem! (https://github.com/ReactiveX/RxJava/issues/1889) , I have to add .publish().refCount() to the created observable,but the following still don't work
```scala
    import outwatch.dom._
    import rxscalajs.Observable

    val hd: Handler[Event] =createHandler() //sink and observable
    val ob=hd.publish.refCount
    ob.map(x=>println("toggle"))//not working here!
    //Observable.interval(10).take(20).subscribe(x=>println("aa")) // working!
    val root = div(
      label("Hide view"),
      input(tpe := "checkbox", change --> hd),
      h2(hidden <-- ob.map(_.target.asInstanceOf[HTMLInputElement].checked).map(x=>{println("x");x}), "Visible!")
    )

    OutWatch.render(sel,root) //sel here is a selector string

```

**Comment by fdietze** [comment] 2018-01-03 19:57
Thanks for reporting. We ported OutWatch on the current master branch to Monix and IO Monads, so a lot has changed since the last release. I encourage you to try the latest master branch via jitpack as described in the readme. It should be quite stable. If you have any questions, please ask.

**Comment by mariusmuja** [comment] 2018-01-03 20:05
> 'toggle' is not printed ,but 'x' is printed,is that expected behavior?

'toggle' is not printed in your example because you're not subscribing to the observable, so the `.map()` is never executed. If you do:
```scala
 hd.map(x=>println("toggle")).subscribe()
```
or 
```scala
 hd.subscribe(x=>println("toggle"))
```
then 'toggle' should be printed.

'x' is printed because you're feeding the observable to the `hidden` attribute, which results in a subscription being created.

**Comment by doofin** [comment] 2018-01-05 07:23
I have changed to subscribe,but without add `.share` to the observable it still doesn't work.So is there a way to modify the `observable` part of a `handler` and put it back?

**Comment by mariusmuja** [comment] 2018-01-06 19:35
Can you provide the example where it doesn't work?

**Comment by cornerman** [comment] 2018-07-30 12:19
We are now running on monix and not on rxjs anymore. Additionally a lot of code has changed since the issue was created.

I cannot reproduce this problem, so I will close this. Please feel free to reopen if the problem still exists.

**Closed by cornerman** 2018-07-30 12:19 UTC
